read: read.cpp
	c++ read.cpp -o read -I/home/kgdaq/vme-test/include -Wall -I/home/kgdaq/vme-test/pcivme/lib -I/home/kgdaq/vme-test/pcivme/driver /home/kgdaq/vme-test/pcivme/lib/pcivme_ni.c `root-config --cflags --libs` /home/kgdaq/vme-test/include/ConfigFile.cpp
